### ISSUE TITLE
Difficulty of separating multiple values in IDs/Education/Employment

### ISSUE THREAD

**Issue by mjwhitton** [ostephens/orcid-node#1]
I have used the demo version and found it useful (I found Scopus ID the best way of matching witho our systems). It would have beem easier to use if where a person had multiple IDs/Education/Employment they were separated by a specific character like a ';'.

**Comment by ostephens** [comment]
Thanks @mjwhitton. I've updated the app to include a semi-colon as a separator in multi-value fields - hopefully that will help
