### ISSUE TITLE
Add a license to indicate how this project can be used

### ISSUE THREAD

**Issue by bbranan** [ostephens/orcid-node#4]
This is a great app, thank you for creating it! Unfortunately, I've not been able to find a license associated with the code. As noted here: https://choosealicense.com/no-permission/, having no license limits my ability to reuse what you've made. I assume this is simply an oversight.

Github helps to simplify the process of adding a LICENSE file by providing ready-made templates, as noted in the instructions here: https://help.github.com/en/articles/adding-a-license-to-a-repository.

**Comment by ostephens** [comment]
Hi @bbranan - thanks for prompting me on this. I created the app as part of a contract with another organisation and I'm discussing licensing options with them now - once that's been resolved I'll add a license

**Comment by ostephens** [comment]
Done - thanks for the prompt - now licensed under Apache 2 and a license file added to the repo
